### ISSUE TITLE
hope to handle 308 statecode in rbenv-install.ps1/function dl()

### ISSUE THREAD

**Issue by Jump-Wang-111** [ccmywish/rbenv-for-windows#18] opened 2023-04-29 06:49 UTC
I am installing ruby for the first time. During the installation process, It need to visit https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/github-release/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.2 -1/rubyinstaller-devkit-3.2.2-1-x64.exe to download, but the powershell script fails with 308, I use the browser to download from this URL succcessfully, because 308 returns a redirected address.

I think a good way to solve this is to add 308 in `$handledCodes` just like this:
```
$handledCodes = @(
            [System.Net.HttpStatusCode]::MovedPermanently,  # HTTP 301
            [System.Net.HttpStatusCode]::Found,             # HTTP 302
            [System.Net.HttpStatusCode]::SeeOther,          # HTTP 303
            [System.Net.HttpStatusCode]::TemporaryRedirect  # HTTP 307
	    [System.Net.HttpStatusCode]::PermanentRedirect	# HTTP 308
        )
```
however it doesn't work. Finally I change the condition of statecode to solve the problem like:
```
if ($handledCodes -notcontains $redirectRes.StatusCode -and $redirectRes.StatusCode -ne 308 ) {
            throw $exc
        }
```
I hope the support to 308 can be added and I still feel confused about why change `$handledCodes` don't work?

**Comment by ccmywish** [comment] 2023-04-29 07:42
Hi @Jump-Wang-111 

Thanks for your feedback and your patience in trying to solve it by yourself. 👍 In effect, the issue is reported several times, see #7 

I speculate you're using `PowerShell v5.x series`. Please update to `pwsh 7.x series` as a solution. You don't need to change the source code. 

I'll dig into the problem in detail later.

**Comment by Jump-Wang-111** [comment] 2023-05-03 14:46
ohhhh, I did not see that issue before. My PowerShell is indeed version 5.1. Thanks!

**Comment by ccmywish** [comment] 2023-05-19 16:38
- PowerShell `v5.0` was released in `2016`
- PowerShell `v5.1` was released in `2017`

However, `308 status code` is only published in `2015` (very young), many clients can't recognize it. I think `PowerShell v5 series` are so. 

I'll close this issue. If you have some doubts, please re-open it. Thanks.

**Comment by ccmywish** [comment] 2023-05-20 02:17
I've changed my mind, because I think it's easy to fix.

As I've said above, it's because PowerShell `v5.x` can't recognize `[System.Net.HttpStatusCode]::PermanentRedirect`, but we can just write the `308` directly to fix it.

**Comment by ccmywish** [comment] 2023-05-20 02:27
I've patched the code.

I've tested it on my machine and it works. Please check it yourself If you have time. 🤝

Thanks for reporting it! 👍

**Closed by ccmywish** 2023-05-20 02:27 UTC
